spring:
  zipkin:
    baseUrl:  http://zipkin-svc:9411
eureka:
  instance:
    preferIpAddress:  true
  client:
    fetchRegistry:  true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
